version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: true
hooks:
  AfterInstall:
    - location: aws/scripts/install-dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: aws/scripts/application-start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: aws/scripts/application-stop.sh
      timeout: 300
      runas: ec2-user

file_exists_behavior: OVERWRITE