version: 0.0
os: linux
files:
  - source: /aws
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: install-dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: application-start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: application-stop.sh
      timeout: 300
      runas: ec2-user